docs/AboutUs.md

Change Doe John to Akshan

---

src/main/java/Balance.java

Created Balance class to show list of members the user owes money to.
Class currently uses Hash Map to store user & balance value pairs - will update for use with other classes once available.

Create Balance class

---

.idea/.gitignore
.idea/misc.xml
.idea/vcs.xml
src/main/java/seedu/duke/User.java

Add user class

---

src/test/java/seedu/duke/HelpTest.java

JUnit test for help menu functionality for #9

JUnit test for help functionality

---

src/main/java/seedu/duke/Expense.java
src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/Parser.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Got it to work
"Freaking dumb" -Shaoliang

Integrate everything

---

docs/AboutUs.md
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/Parser.java
src/test/java/seedu/duke/GroupTest.java

Reverts AY2324S2-CS2113-T15-3/tp#45
i am sorry i will try harder

Revert "Addded use of optional to handle null and fixed checkstyle"

---

src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/GroupCommand.java
src/main/java/seedu/duke/Parser.java
src/test/java/seedu/duke/AddUserTest.java
src/test/java/seedu/duke/GroupTest.java

Changed a lot of stuff please review

Refactor group, group commands into an optional context in Parser.java

---

src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/GroupCommand.java
src/main/java/seedu/duke/Parser.java
src/test/java/seedu/duke/AddUserTest.java
src/test/java/seedu/duke/GroupTest.java

Reverts AY2324S2-CS2113-T15-3/tp#49

Revert "Refactor group, group commands into an optional context in Parser.java"

---

docs/DeveloperGuide.md

Will add UML diagrams later. Feature added under Design & Implementation section. Feel free to reformat

Add member feature in DG

---

docs/DeveloperGuide.md
src/main/java/seedu/duke/Expense.java
src/test/java/seedu/duke/AddUserTest.java

Add Expense feature in implementation section and populate v1.0  user stories in developer guide.

Modify developer guide

---

docs/DeveloperGuide.md

Added information in DeveloperGuide

edit DeveloperGuide.md

---

src/main/java/seedu/duke/Balance.java
src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/Parser.java
src/test/java/seedu/duke/BalanceTest.java

Add new expenseList param to Group class.
Added checks if user is currently in a group to expense and balance switch statements in Parser. 
Made printBalance() callable from balance switch statement in Parser. 
Change var type from ArrayList to List in Balance methods and edited BalanceTest.

Integrate Balance class with Group and Expense classes

---

src/main/java/seedu/duke/UniversalExceptions.java

UniversalException boiler plate

Add UniversalExceptions.java

---

build.gradle
src/main/java/seedu/duke/Balance.java
src/main/java/seedu/duke/Expense.java
src/main/java/seedu/duke/Help.java
src/main/java/seedu/duke/Parser.java
src/test/java/seedu/duke/BalanceTest.java
src/test/java/seedu/duke/ExpenseTest.java

close #67 
This is what the equal and unequal split command and output look like:

Add description and unequal split to Expenses

---

build.gradle
src/main/java/seedu/duke/Balance.java
src/main/java/seedu/duke/Expense.java
src/main/java/seedu/duke/Pair.java
src/main/java/seedu/duke/Parser.java
src/test/java/seedu/duke/BalanceTest.java
text-ui-test/EXPECTED.TXT

Copied CS2030 utility function Pair class for use with Expense and Balance class.

Create Pair class

---

.gitignore
src/main/java/seedu/duke/Expense.java
src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/GroupStorage.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/exceptions/GroupLoadException.java
src/main/java/seedu/duke/exceptions/GroupSaveException.java
src/main/java/seedu/duke/storage/FileIO.java
src/main/java/seedu/duke/storage/FileIOImpl.java
src/main/java/seedu/duke/storage/GroupFilePath.java
src/main/java/seedu/duke/storage/GroupStorage.java
src/test/java/seedu/duke/storage/GroupStorageTest.java

All to review please. Note that groups will be saved as their own .txt files in the format shown in the picture

Implement database

---

src/main/java/seedu/duke/CurrencyConversions.java
src/main/java/seedu/duke/Money.java
src/main/java/seedu/duke/Parser.java
src/test/java/seedu/duke/CurrencyConversionsTest.java
src/test/java/seedu/duke/MoneyTest.java

Please take a look.
Not sure if this paradigm is what we need
Resolves #62

Add currency exchange functionality

---

src/main/java/seedu/duke/Pair.java

Add citation

---

src/main/java/seedu/duke/MessageType.java
src/main/java/seedu/duke/UserInterface.java
src/test/java/seedu/duke/UserInterfaceTest.java

Please approve my cat printing
Call printMessage() function with an optional MessageType param
Message frame printed is either default cat, success cat, or error cat. Should print success cat if command is successful, and error cat if command has errors. 
Resolves #59

Create UserInterface Class

---

src/main/java/seedu/duke/Expense.java
src/main/java/seedu/duke/Parser.java
src/test/java/seedu/duke/BalanceTest.java

When user enters 'bye' current group is saved to file.

Fix issue with end programme

---

src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/storage/GroupNameChecker.java
src/main/java/seedu/duke/storage/GroupStorage.java

Able to check if groups exists in data before creating. Added GroupNameChecker class. Fix for issue 2 as discussed with mukund

More Database fix

---

src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/exceptions/GroupLoadException.java
src/main/java/seedu/duke/exceptions/GroupSaveException.java
src/main/java/seedu/duke/exceptions/UniversalExceptions.java
src/main/java/seedu/duke/storage/GroupStorage.java

Branch from where I left off from Monday night

Partial fix database

---

src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/GroupCommand.java
src/main/java/seedu/duke/Parser.java

Fixed bugs that allow users to enter a group when currently in another group. 
Fixed exit group function bug that allows users to exit without inputting correct group name.

fixed exit and enter group bugs

---

src/main/java/seedu/duke/GroupCommand.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/exceptions/GroupDeleteException.java
src/main/java/seedu/duke/storage/FileIO.java
src/main/java/seedu/duke/storage/FileIOImpl.java
src/main/java/seedu/duke/storage/GroupStorage.java

Previous PR couldn't load group at all. Please merge and pull

Fix Loading

---

src/main/java/seedu/duke/Expense.java
src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/commands/ExpenseCommand.java
src/main/java/seedu/duke/storage/GroupStorage.java
src/test/java/seedu/duke/ExpenseTest.java

close #139 
close #137 
close #135 
close #134 
close #133 
close #131 
close #130 
close #125 
close #118 
close #115 
close #112

add delete expense feature and fix all issues from pe-d

---

src/main/java/seedu/duke/GroupCommand.java
src/main/java/seedu/duke/exceptions/GroupDeleteException.java
src/main/java/seedu/duke/storage/FileIOImpl.java

Allows user to delete saved group before needing to load them first

Update delete group

---

src/main/java/seedu/duke/Balance.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/commands/BalanceCommand.java

Separetes Balance class into Balance and BalanceCommand to ensure SLAP in Parser class
Resolves #167 #136

Update Balance Class

---

src/main/java/seedu/duke/Balance.java
src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/Parser.java

Rewrite Settle to work with Money

Rewrite Settle

---

src/main/java/seedu/duke/Group.java
src/main/java/seedu/duke/Help.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/commands/GroupCommand.java
src/test/java/seedu/duke/GroupTest.java
src/test/java/seedu/duke/HelpTest.java
src/test/java/seedu/duke/SettleTest.java

Also made minor edits to help menu

Fixed group and moved to command package
